const specialDates = [
  {
    month: 0,
    date: 1,
    event: "New Year's Day",
    bgcolor: "#674dff",
    color: "white",
    holiday: false,
  },
  {
    month: 1,
    date: 4,
    event: "Independence Day",
    bgcolor: "red",
    color: "white",
    holiday: true,
  },
  {
    month: 1,
    date: 14,
    event: "Valentine's Day",
    bgcolor: "Pink",
    color: "black",
    holiday: true,
  },
  {
    month: 2,
    date: 17,
    event: "St. Patrick's Day",
    bgcolor: "green",
    color: "white",
    holiday: false,
  },
  {
    month: 3,
    date: 1,
    event: "April Fool's Day",
    bgcolor: "orange",
    color: "white",
    holiday: false,
  },
  {
    month: 4,
    date: 5,
    event: "Cinco de Mayo",
    bgcolor: "red",
    color: "white",
    holiday: false,
  },
  {
    month: 5,
    date: 21,
    event: "Father's Day",
    bgcolor: "blue",
    color: "white",
    holiday: false,
  },
  {
    month: 6,
    date: 1,
    event: "National Doctor's Day",
    bgcolor: "cyan",
    color: "black",
    holiday: false,
  },
  {
    month: 7,
    date: 15,
    event: "Assumption of Mary",
    bgcolor: "blue",
    color: "white",
    holiday: false,
  },

  {
    month: 8,
    date: 7,
    event: "Labor Day",
    bgcolor: "green",
    color: "white",
    holiday: false,
  },
  {
    month: 9,
    date: 31,
    event: "Halloween",
    bgcolor: "orange",
    color: "white",
    holiday: false,
  },
  {
    month: 10,
    date: 26,
    event: "Thanksgiving",
    bgcolor: "brown",
    color: "white",
    holiday: false,
  },
  {
    month: 11,
    date: 25,
    event: "Christmas",
    bgcolor: "red",
    color: "white",
    holiday: true,
  },
];
